<?php

return [
    'ATV',
    'Ararat',
    'MTV.AM',
    'MTV.AM HD',
    'PanArmenian',
    'Ար',
    'Արմենիա Tv',
    'Արմենիա Tv HD',
    'Արմնյուզ',
    'Դար 21',
    'Երկիր մեդիա',
    'Կենտրոն',
    'Հ1',
    'Հ1 International',
    'Հ2',
    'Հ3',
    'Շանթ',
    'Շողակաթ',
    'Playboy TV',
    'Русская Ночь',
    'Первый канал',
    'Телеканал «Россия»',
    'РТР-Планета',
    'НТВ-Мир',
    'E!',
    'Food Network',
    '5 канал (Украина)',
    'HTH',
    'Discovery Channel',
    'Nat Geo Wild',
    'Наш футбол',
    'КХЛ ТВ',
    'BBC World News',
    'Надежда',
    'Eurosport 1',
    'Animal Planet',
    'Travel Channel',
    'Travel',
    'Россия-Культура',
    'Россия Культура',
    'Россия 1',
    'Пятый Канал',
    'OCEAN-TV',
    'Freeform',
    'Bloomberg',
    'НТВ2',
    'Че',
    'РБК',
    'Toot',
    'Матч! HD'
];