<?php

return ['excludeChannels' =>
    [
        'ATV',
        'Ararat',
        'MTV.AM',
        'MTV.AM HD',
        'PanArmenian',
        'Ար',
        'Արմենիա Tv',
        'Արմենիա Tv HD',
        'Արմնյուզ',
        'Դար 21',
        'Երկիր մեդիա',
        'Կենտրոն',
        'Հ1',
        'Հ1 International',
        'Հ2',
        'Հ3',
        'Շանթ',
        'Շողակաթ',
        'Первый канал',
        'Телеканал «Россия»',
        'РТР-Планета',
        'НТВ-Мир',
        'E!',
        'Food Network',
        'Discovery Channel',
        'Nat Geo Wild',
        'BBC World News',
        'Надежда',
        'Animal Planet',
        'Travel Channel',
        'Travel',
        'Россия Культура',
        'Россия 1',
        'Пятый Канал',
        'OCEAN-TV',
        'Freeform',
        'Bloomberg',
        'НТВ2',
        'Че',
        'РБК',
        'Toot',
    ]
];